"""Add verification levels, entity types, and legal filters

Revision ID: 3a236e55a4d6
Revises: 32b48a2c1c31
Create Date: 2026-04-26 22:40:28.832244

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a236e55a4d6'
down_revision: Union[str, Sequence[str], None] = '32b48a2c1c31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('verification_level', sa.Enum('NONE', 'BASIC', 'CONTACTS', 'PASSPORT', name='verificationlevel'), nullable=True))
    op.add_column('profiles', sa.Column('entity_type', sa.Enum('PHYSICAL', 'LEGAL', 'UNKNOWN', name='entitytype'), nullable=True))
    op.add_column('profiles', sa.Column('company_name', sa.String(), nullable=True))
    op.add_column('profiles', sa.Column('fio', sa.String(), nullable=True))
    op.add_column('profiles', sa.Column('location', sa.String(), nullable=True))
    op.add_column('profiles', sa.Column('email', sa.String(), nullable=True))
    op.add_column('profiles', sa.Column('phone', sa.String(), nullable=True))
    op.add_column('profiles', sa.Column('language_proficiency', sa.String(), nullable=True))
    op.add_column('profiles', sa.Column('work_authorization', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profiles', 'work_authorization')
    op.drop_column('profiles', 'language_proficiency')
    op.drop_column('profiles', 'phone')
    op.drop_column('profiles', 'email')
    op.drop_column('profiles', 'location')
    op.drop_column('profiles', 'fio')
    op.drop_column('profiles', 'company_name')
    op.drop_column('profiles', 'entity_type')
    op.drop_column('profiles', 'verification_level')
    # ### end Alembic commands ###
