"""Add projects and bids tables

Revision ID: 88a719b0ac0c
Revises: 4b347f66e5e7
Create Date: 2026-04-29 19:50:28.750534

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88a719b0ac0c'
down_revision: Union[str, Sequence[str], None] = '4b347f66e5e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employer_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('budget', sa.Integer(), nullable=True),
    sa.Column('required_specialization', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('OPEN', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', name='projectstatus'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['employer_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_id'), 'projects', ['id'], unique=False)
    op.alter_column('bids', 'project_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('bids', 'worker_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('bids', 'status',
               existing_type=sa.VARCHAR(length=8),
               nullable=True)
    op.alter_column('bids', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bids', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('bids', 'status',
               existing_type=sa.VARCHAR(length=8),
               nullable=False)
    op.alter_column('bids', 'worker_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('bids', 'project_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index(op.f('ix_projects_id'), table_name='projects')
    op.drop_table('projects')
    # ### end Alembic commands ###
