"""Add projects and bids tables

Revision ID: 88a719b0ac0c
Revises: 4b347f66e5e7
Create Date: 2026-04-29 19:50:28.750534

Phase 5 fix:
   Original autogenerated migration использовала прямые `op.alter_column`,
   которые SQLite не поддерживает (ошибка "near 'ALTER': syntax error").
   Переписано на `op.batch_alter_table` — он работает и в SQLite (через
   recreate-and-copy), и в PostgreSQL (transparent passthrough).
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88a719b0ac0c'
down_revision: Union[str, Sequence[str], None] = '4b347f66e5e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.create_table(
        'projects',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('employer_id', sa.Integer(), nullable=True),
        sa.Column('title', sa.String(), nullable=False),
        sa.Column('description', sa.Text(), nullable=False),
        sa.Column('budget', sa.Integer(), nullable=True),
        sa.Column('required_specialization', sa.String(), nullable=True),
        sa.Column(
            'status',
            sa.Enum('OPEN', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', name='projectstatus'),
            nullable=True,
        ),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('(CURRENT_TIMESTAMP)'),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(['employer_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_projects_id'), 'projects', ['id'], unique=False)

    # batch_alter_table работает и в SQLite (recreate-and-copy), и в PostgreSQL
    with op.batch_alter_table('bids') as batch_op:
        batch_op.alter_column(
            'project_id', existing_type=sa.INTEGER(), nullable=True,
        )
        batch_op.alter_column(
            'worker_id', existing_type=sa.INTEGER(), nullable=True,
        )
        batch_op.alter_column(
            'status', existing_type=sa.VARCHAR(length=8), nullable=True,
        )
        batch_op.alter_column(
            'created_at',
            existing_type=sa.DATETIME(),
            nullable=True,
            existing_server_default=sa.text('(CURRENT_TIMESTAMP)'),
        )


def downgrade() -> None:
    """Downgrade schema."""
    with op.batch_alter_table('bids') as batch_op:
        batch_op.alter_column(
            'created_at',
            existing_type=sa.DATETIME(),
            nullable=False,
            existing_server_default=sa.text('(CURRENT_TIMESTAMP)'),
        )
        batch_op.alter_column(
            'status', existing_type=sa.VARCHAR(length=8), nullable=False,
        )
        batch_op.alter_column(
            'worker_id', existing_type=sa.INTEGER(), nullable=False,
        )
        batch_op.alter_column(
            'project_id', existing_type=sa.INTEGER(), nullable=False,
        )

    op.drop_index(op.f('ix_projects_id'), table_name='projects')
    op.drop_table('projects')
